Project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.debug import default_urlconf
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sr.urls')),
    url(r'^$', default_urlconf),
]

sr/urls.py
from django.conf.urls import url, include
from . import views


from django.views.static import serve
app_name = 'sr'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^register/$', views.register, name='register'),
    url(r'^decks/$', views.decks, name='decks'),
    url(r'^why-edumate/$', views.why_edumate, name='why-edumate'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^contact-success/$', views.contact_success, name='contact-success'),
    url(r'^browse-decks/$', views.browse_decks, name='browse-decks'),
    url(r'^getting-started/$', views.getting_started, name='getting-started'),
    url(r'^decks/details/(?P<deck_name>.*)/$', views.deck_details, name='deck-details'),
    url(r'^decks/add-decks/(?P<deck_name>.*)/$', views.add_deck, name='add-deck'),
    url(r'^review/(?P<deck_name>.*)/$', views.review, name='review'),
    url(r'^test/$', views.test, name='test'),
]

sr/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Deck(models.Model):
    name = models.CharField(max_length=100, default="Orphaned", db_index=True, unique=True)
    description = models.TextField(default="")
    last_added_to = models.DateTimeField(auto_now_add=True)
    last_modified_content = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class Card(models.Model):
    front = models.TextField()
    back = models.TextField()
    deck = models.ForeignKey(Deck, db_index=True)
    when_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    summary = models.CharField(max_length=200, blank=True, default="")
    def __str__(self):
        if self.summary:
            return self.summary
        return self.front[:200]

class Scheduler(models.Model):
    name = models.CharField(max_length=100)
    ref = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class CardRelationsSchema(models.Model):
    name = models.CharField(max_length=100, unique=True)
    ref = models.CharField(max_length=200, blank=True, default='')
    blob = models.BinaryField(blank=True, null=True, default=None)
    def __str__(self):
        return self.name

class CardRelationsSet(models.Model):
    name = models.CharField(max_length=100, blank=True, default='')
    schema = models.ForeignKey(CardRelationsSchema)
    deck = models.ForeignKey(Deck)
    last_modified = models.DateTimeField(auto_now_add=True)
    ref = models.CharField(max_length=200, blank=True, default='')
    blob = models.BinaryField(blank=True, null=True, default=None)
    def __str__(self):
        return self.deck.name + ": " + self.schema.name

class DeckInstance(models.Model):
    deck = models.ForeignKey(Deck, db_index=True)
    user = models.ForeignKey(User, db_index=True)
    when_created = models.DateTimeField(auto_now_add=True)
    scheduler = models.ForeignKey(Scheduler, null=True)
    card_relations_set = models.ForeignKey(CardRelationsSet, blank=True, null=True)
    reviews_done = models.IntegerField(default=0)
    def __str__(self):
        return self.deck.name + "; " + self.user.username
    class Meta:
        unique_together = ("deck", "user")

class ScheduledReview(models.Model):
    card = models.ForeignKey(Card, db_index=True)
    deck_instance = models.ForeignKey(DeckInstance, db_index=True)
    when_scheduled = models.DateTimeField(auto_now_add=True, db_index=True)
    when_due = models.DateTimeField(db_index=True)
    done = models.BooleanField(default=False)
    def __str__(self):
        return "Card in " + str(self.deck_instance.deck) + " due on " + str(self.when_due)
    class Meta:
        indexes = [
            models.Index(fields=['deck_instance', 'done']),
        ]

class FinishedReview(models.Model):
    scheduled_review = models.ForeignKey(ScheduledReview)
    '''
    WRONG = 'WR'
    HARD = 'HR'
    EASY =  'EZ'
    SCORE_CHOICES = (
        (WRONG, "Incorrect"),
        (HARD, "Correct but with difficult"),
        (EASY, "Correct and easy"),
    )
    score = models.CharField(max_length=2, choices=SCORE_CHOICES)
    '''
    score = models.IntegerField()
    answer_long_form = models.TextField(blank=True, default='')
    when_reviewed = models.DateTimeField(auto_now_add=True, db_index=True)
    def __str__(self):
        return ("Card in " + str(self.scheduled_review.deck_instance.deck) + " reviewed on " + 
                str(self.when_reviewed) + ": " + str(self.score))

# hack to be used until mail server is set up
class ContactForm(models.Model):
    email = models.EmailField()
    subject = models.TextField()
    message = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    def __str__(self):
        return subject

sr/forms.py
# for most purposes we use django library forms...
from django import forms

class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

sr/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseBadRequest
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from forms import ContactForm
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
import datetime
from django.db.models import Min, Count
from django.template import Context, Template
import sr.models
import random

def index(request):
    return render(request, 'sr/index.html')

def test(request):
    return render(request, 'sr/test.html')

### COPIED OVER
def decks(request):
    if (request.user.is_authenticated()):
        instance_list = sr.models.DeckInstance.objects.filter(user=request.user)
        due_list = [len(sr.models.ScheduledReview.objects.filter(deck_instance=x).filter(done=False, when_due__lt=datetime.datetime.now())) for x in instance_list]
        return render(request, 'sr/decks.html', {'instance_list': instance_list, 'due_list': due_list})
    else:
        return HttpResponseRedirect(reverse('sr:login'))

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return HttpResponseRedirect(reverse('sr:decks'))

    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

def why_edumate(request):
    return render(request, 'sr/why-edumate.html')

def contact(request):
    success = None
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            success = True
            sr.models.ContactForm.objects.create(email=form.cleaned_data['email'],
                                              subject=form.cleaned_data['subject'],
                                              message=form.cleaned_data['message'])
        else:
            success = False
    return render(request, 'sr/contact.html', {'form': ContactForm(), 'success': success})

def contact_success(request):
    return render(request, 'sr/contact-success.html')

def browse_decks(request):
    added = {}
    if (request.user.is_authenticated()):
        added = {di.deck for di in sr.models.DeckInstance.objects.filter(user=request.user)}
    notAdded = [d for d in sr.models.Deck.objects.all() if d not in added]
    added = list(added)
    countsAdded = [len(sr.models.Card.objects.filter(deck=d)) for d in added]
    countsNotAdded = [len(sr.models.Card.objects.filter(deck=d)) for d in notAdded]
    return render(request, 'sr/browse-decks.html', {'added': added, 'notAdded': notAdded, 'countsAdded': countsAdded,
                                                    'countsNotAdded': countsNotAdded})

def add_deck(request, deck_name):
    decks = sr.models.Deck.objects.filter(name=deck_name)
    if not decks:
        raise Http404("No deck with name \"" + deck_name + "\" exists.")
    if (request.user.is_authenticated()):
        di = sr.models.DeckInstance(deck=decks[0], user=request.user, scheduler=None)
        # if user attempts to add duplicate deck instance, update nothing
        try:
            di.save()
            for c in sr.models.Card.objects.filter(deck=di.deck):
                newReview = sr.models.ScheduledReview(card=c, deck_instance=di, when_due=datetime.datetime.now())
                newReview.save()
        except IntegrityError:
            pass
        return HttpResponseRedirect(reverse('sr:decks'))
    else:
        return HttpResponseRedirect(reverse('sr:login'))

def review(request, deck_name):
    if request.user.is_authenticated():
        try:
            d = sr.models.Deck.objects.get(name=deck_name)
            di = sr.models.DeckInstance.objects.get(user=request.user, deck=d)
        except ObjectDoesNotExist:
            raise Http404("Currently you do not have access to deck \"" + deck_name + "\".")
        if request.method == 'POST':
            try:
                rev = sr.models.ScheduledReview.objects.get(pk=int(request.POST['id']))
                fr = sr.models.FinishedReview(scheduled_review=rev, score=int(request.POST['submit']))
                if fr.score not in [0, 1, 2]:
                    raise ValueError
                rev.done = True
                if di.scheduler:
                    newReview = di.scheduler.schedule(di, rev)
                else:
                    newReview = sr.models.ScheduledReview(card=rev.card, deck_instance=rev.deck_instance,
                                                          when_due=datetime.datetime.now() + datetime.timedelta(days=1))
                di.reviews_done += 1
                fr.save()
                rev.save()
                newReview.save()
                di.save()
                #return HttpResponse(str(rev) + ' ' + str(rev.id))
            except (ValueError, ObjectDoesNotExist):
                raise HttpResponseBadRequest('Invalid form input.')
        rev = sr.models.ScheduledReview.objects.filter(deck_instance=di, done=False).earliest('when_due')
        if rev.when_due > datetime.datetime.now(rev.when_due.tzinfo):
            return render(request, 'sr/done-reviewing.html', {'deck_name': deck_name})
        card = {'front': Template(rev.card.front).render(Context({})),
                'back': Template(rev.card.back).render(Context({})),}
        return render(request, 'sr/review.html', {'card': card, 'id': rev.pk})
    else:
        return HttpResponseRedirect(reverse('sr:login'))

def getting_started(request):
    return render(request, 'sr/getting-started.html')

def deck_details(request, deck_name):
    matches = sr.models.Deck.objects.filter(name=deck_name)
    if not matches:
        raise Http404("No deck with name \"" + deck_name + "\" exists.")
    return render(request, 'sr/deck-details.html', {'deck': matches[0]})

sr/templates/sr/base.html
<!-- COPIED OVER; NOT FIXED -->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<style>
body {
    padding-top: 70px;
}
</style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- favicon: <link rel="icon" href="../../favicon.ico"> -->

    <title>{% block title %}Edumate{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous"> -->
    {% load static %}
    <link href="{% static "sr/css/navbar-fixed-top.css" %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>
    {% block head_additions %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color: #F0F0F0;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'sr:index' %}">Edumate</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'sr:why-edumate' %}">Why Edumate?</a></li>
                    <li><a href="{% url 'sr:getting-started' %}">Getting started</a></li>
                    <li><a href="{% url 'sr:browse-decks' %}">Browse decks</a></li>
                    <li><a href="{% url 'sr:contact' %}">Contact</a></li>

                    <!--
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                    -->

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'sr:decks' %}">My Decks</a></li>
                    <!-- <li><a href="/sr/account-home">My Account</a></li> -->
                    <li><a href="{% url 'sr:logout' %}">Sign out<span class="sr-only">(current)</span></a></li>
                    {% else %}
                    <li><a href="{% url 'sr:register' %}">Sign up</a></li>
                    <!-- <li><a href="/sr/login">Sign in</a></li> -->
                    <li><a href="{% url 'sr:login' %}">Sign in</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

    <!-- temporary hack -->
    <!-- <br/>
    <br/>
    <br/>
    <br/> -->
    {% block content %}
    {% endblock content %}

    {% block scripts %}
    {% endblock %}
    </body>
</html>

sr/templates/sr/browse-decks.html
{% extends 'sr/base.html' %}
{% load index %}

{% block content %}
<div class="container">
    <h1>Public decks</h1>
    <table class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Deck name</th>
                <th>Number of cards</th>
                <th>Deck details</th>
                <th>Subscribe to deck</th>
            </tr>
        </thead>
        <tbody>
            {% for deck in notAdded %}
            <tr>
                <td>{{ deck.name }}</td>
                <td>{{ countsNotAdded|index:forloop.counter0 }}</td>
                <td><a href="{% url 'sr:deck-details' deck_name=deck.name %}">Details</a></td>
                <td><a href="{% url 'sr:add-deck' deck_name=deck.name %}">Add to library</a></td>
            </tr>
            {% endfor %}
            {% if added and notAdded %}
            <tr border-bottom: 1px solid black;></tr>
            {% endif %}
            {% for deck in added %}
            <tr>
                <td>{{ deck.name }}</td>
                <td>{{ countsAdded|index:forloop.counter0 }}</td>
                <td><a href="{% url 'sr:deck-details' deck_name=deck.name %}">Details</a></td>
                <td>Already added</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

sr/templates/sr/contact-success.html
{% extends 'sr/base.html' %}

{% block content %}
<div class="container">
    Thank you for your feedback!
</div>
{% endblock %}

sr/templates/sr/contact.html
{% extends 'sr/base.html' %}

{% block content %}
<div class="container">
    <h1>Contact Us</h1>
    <form method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <div class="form-actions">
            <button type="submit">Send</button>
        </div>
    </form>
    {% if success == True %}
    <br>
    Thank you for your feedback!
    {% elif success == False %}
    <br>
    <font color="red">There was an error submitting your feedback. Did you input a valid e-mai address?</font>
    {% endif %}
</div>
{% endblock %}

sr/templates/sr/deck-details.html
{% extends 'sr/base.html' %}

{% block content %}
<div class="container">
    <h1>{{ deck.name }}</h1>
    <p>{{ deck.description }}</p>
</div>
{% endblock %}

sr/templates/sr/decks.html
<!-- COPIED OVER; NOT FIXED -->
{% extends "sr/base.html" %}
{% load index %}
{% block content %} 

{% if user.is_authenticated %}
<div class="container">
    <h1>Your decks</h1>
    {% if instance_list %}
    <table class="table table-striped" style="max-width: 750px;">
        <thead>
            <tr>
                <th>Deck name</th>
                <th>Cards due</th>
                <th>Reviews completed</th>
                <th>Deck details</th>
            </tr>
        </thead>
        <tbody>
            {% for instance in instance_list %}
            <tr>
                <td>{{ instance.deck.name }}</td>
                {% if due_list|index:forloop.counter0 > 0 %}
                <td><a href="{% url 'sr:review' deck_name=instance.deck.name %}">{{ due_list|index:forloop.counter0 }} - Review now</a></td>
                {% else %}
                <td>0</td>
                {% endif %}
                <td>{{ instance.reviews_done }}</td>
                <td><a href="{% url 'sr:deck-details' deck_name=instance.deck.name %}">Details</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    You don't have any decks yet! Go ahead and <a href="{% url 'sr:browse-decks' %}">add some.</a>
    {% endif %}
</div>
<br>
{% endif %}

<div class="container">
    <h1>Deck search</h1>
    <p><a href="{% url 'sr:browse-decks' %}">Click here</a> to browse and add decks.</p>
</div>

{% endblock %}

sr/templates/sr/done-reviewing.html
{% extends 'sr/base.html' %}

{% block content %}

<div class="container">
  <h1>Finished all due reviews for deck "{{ deck_name }}".</h1>
</div>

{% endblock %}

sr/templates/sr/getting-started.html
	{% extends "sr/base.html" %}

{% block content %}
<div class="container">
    <h2>First steps</h2>
    <p>Try reading the <a href="{% url 'sr:why-edumate' %}">overview</a> to get a basic understanding of what Edumate does, or jump right in by
        <a href="{% url 'sr:register' %}">creating an account!</a></p>
    <h2>How to use Edumate</h2>
    <p>Once you have an account, subscribe to one or more decks on the <a href="{% url 'sr:browse-decks' %}">browse decks page</a>. Decks are composed of
       flashcards, which are scheduled for review by Edumate. You can view your decks, see what is due, and initiate review sessions on the
       <a href="{% url 'sr:decks' %}">my decks page</a>.
    <p>Each card consists of a prompt and an answer. The prompt is presented first - try to answer it as best as you can, and then press any key
       to reveal the answer.
       Afterward, indicate your performance: press "Wrong" if you got the item wrong, "Right" if you got it right, and "Trivial" if the item was so easy
       that you don't think you'll need to review it very often.</p>
    <p>Under construction...</p>
</div>
{% endblock %}

sr/templates/sr/index.html
{% extends 'sr/base.html' %}

{% block content %}
<div class="container">
<h1>Welcome to Edumate!</h1>
<br>
<h4><p>Edumate optimizes human learning by applying insights from cognitive psychology. You can jump right in and <a href="{% url 'sr:getting-started' %}">start using Edumate</a>, or
   <a href={% url 'sr:why-edumate' %}>learn more</a> about what Edumate does.</p><h4>
</div>
{% endblock %}

sr/templates/sr/review.html
{% extends 'sr/base.html' %}

{% block content %}

{% load static %}

<div class="container">
  <br>
  <div id="front" style="font-size:48px;">
    {{ card.front|safe }}
  </div>
  <!-- <img src="{% static "sr/JPEG_example_JPG_RIP_050.jpg" %}"> -->
  <!-- <div id="reverse"> -->
  <div id="reverse" style="display: none; font-size:22px;">
    <hr style="border:2px solid #000;">
    <p>{{ card.back|safe }}</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" name="submit" value="0">Wrong</button>
      <button type="submit" name="submit" value="1">Right</button>
      <button type="submit" name="submit" value="2">Trivial</button>
      <input type="hidden" name="id" value="{{ id }}">
    </form>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script>
$(document).keypress(function() {
$("#reverse").css("display", "inline");
});
</script>
{% load static %}
{% endblock %}

sr/templates/sr/test.html
{% extends 'sr/base.html' %}
{% load static %}

{% block head_additions %}
<!-- <link rel="stylesheet" href="{% static "sr/jquery-jvectormap-2.0.3.css" %}" type="text/css" media="screen"/>
  <script src="{% static "sr/jquery.js" %}"></script>
  <script src="{% static "sr/jquery-jvectormap-2.0.3.min.js" %}"></script>
  <script src="{% static "sr/jquery-jvectormap-africa-mill.js" %}"></script>
  <script src="{% static "sr/jquery-jvectormap-europe-mill.js" %}"></script>
-->
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static "sr/jquery-jvectormap-2.0.3.css" %}" type="text/css" media="screen"/>
  <script src="{% static "sr/jquery.js" %}"></script>
  <script src="{% static "sr/jquery-jvectormap-2.0.3.min.js" %}"></script>
  <script src="{% static "sr/jquery-jvectormap-africa-mill.js" %}"></script>
  <script src="{% static "sr/jquery-jvectormap-europe-mill.js" %}"></script>

<div class="container">
<p style="font-size: 36px; text-align: center;">Identify the highlighted country:</p>

<div id="map" style="width: 600px; height:500px; margin: auto;"></div>
  <script>
    $(function(){
      $('#map').vectorMap({map: 'europe_mill',
      regionStyle: {
  initial: {
    fill: 'grey',
    "fill-opacity": 1,
    stroke: 'none',
    "stroke-width": 0,
    "stroke-opacity": 1
  },
  hover: {
    "fill-opacity": 0.8,
    cursor: 'pointer'
  },
  selected: {
    fill: 'red'
  },
  selectedHover: {
  }
},
      backgroundColor: 'white',
      zoomButtons: true,
      selectedRegions: 'FR',
     onRegionTipShow: function(e, label, code){
       e.preventDefault();
}
         

      });
    });
  </script>
</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

sr/templates/sr/why-edumate.html
{% extends "sr/base.html" %}

{% block content %}
<div class="container">
    <h1>Overview</h1>
    <p>Psychological research has discovered ways to optimize human learning. Unfortunately, many of these findings are implemented imperfectly and
    infrequently. After all, most people are not experts in cognitive psychology. And even those who are will find it difficult and
    time-consuming to structure their learning in accordance with the research literature.</p>
    <p>Edumate remeides this gulf between theory and practice. Edumate understands the relevant psychology, so that you don't have to. And Edumate
    manages, tracks, and schedules your study time for you, so that all you have to do is show up and learn.</p>
    <p>Edumate also gathers anonymized data that can be used to inform and improve the learning process. Users can be randomly assigned to
    different scheduling algorithms or parameters to determine what works best. And when used in a classroom setting, Edumate provides
    a detailed view of student mastery of the material.</p>

    <h2>So What Exactly Does Edumate Do?</h2>
    <p>Under construction...</p>
</div>
{% endblock %}